<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="assets/css/style.css">
    <script src="assets/js/accordion.js"></script>
    <title>AEOM</title>
</head>
<body>
    <!-- -------- Navigation bar ----- -->
    <header>
        <a href="index.php" class="logo">AEOM</a>
            <nav>
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="">A propos</a></li>
                    <li><a href="blog.php">Blog</a></li>
                    <li><a href="evenement.php" class="active">Évènements</a></li>
                    <li><a href="">Annonces</a></li>
                    <li><a href="">Donation</a></li>
                </ul>
            </nav>
            <div class="bloc_co">
                <?php if($user == ""): ?>
                    <a href="registerUser.php"><i class="fas fa-user-circle"></i></a>
                <?php elseif($user != ""): ?>
                    <a href="registerUser.php"><span><?= $user ?></span></a>
                    <a href="logOut.php"><i class="fas fa-sign-out-alt"></i></a>
                <?php endif ?>
            </div>
    </header>
    <main class="event">
        <h1>Tout les prochains évènement</h1>
        <section>
            <div class="container">
                <div id="event_box">
                    <?php foreach ($events as $event): ?>
                        <h2><?= $event['date_begin'].' :      '.$event['title'] ?></h2>
                        <div>
                            <p><?= $event['content'] ?></p>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </section>
    </main>

</body>
</html>