<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="assets/css/style.css">
    <script src="assets/js/remark.js"></script>
    <script src="assets/js/accordion.js"></script>
    <title>AEOM</title>
</head>
<body>
    <!-- -------- Navigation bar ----- -->
    <header>
        <a href="index.php" class="logo">AEOM</a>
            <nav>
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="">A propos</a></li>
                    <li><a href="blog.php" class="active">Blog</a></li>
                    <li><a href="evenement.php">Évènements</a></li>
                    <li><a href="">Annonces</a></li>
                    <li><a href="">Donation</a></li>
                </ul>
            </nav>
            <div class="bloc_co">
                <?php if($user == ""): ?>
                    <a href="registerUser.php"><i class="fas fa-user-circle"></i></a>
                <?php elseif($user != ""): ?>
                    <a href="registerUser.php"><span><?= $user ?></span></a>
                    <a href="logOut.php"><i class="fas fa-sign-out-alt"></i></a>
                <?php endif ?>
            </div>
    </header>
    <main class="article">
        <div class="container">
            <p><strong>date de publication </strong> : <?= $objArticle->getDate(); ?></p>
            <p><strong>auteur</strong> : <?= $objArticle->getAuthor(); ?></p>
            <hr>
            <h1><?= $objArticle->getTitle(); ?></h1>
            <figure>
                <?php if($objArticle->getImage() != ""): ?>
                    <img src="assets/img/upload/<?= $objArticle->getImage(); ?>" alt="image">
                <?php else: ?>
                    <img src="https://picsum.photos/200" alt="image">
                <?php endif ?>
                
                <figcaption>tire de l'image</figcaption>
            </figure>
            <p><?= $objArticle->getContent(); ?></p>
            <h2>Commentaires</h2>
            <div class="remarks_container">
                <?php if(!empty($_SESSION['user'])): ?>
                    <div class="editor_box">
                        <input type="text" id="comment"> <button id="send">Envoyer</button> 
                    </div>
                <?php endif; ?>
                <div class="screen">
                    <?php foreach($commentsUsers as $comment): ?>
                    <?php foreach($comment as $author => $remark): ?>
                        <div class="remark">
                            <div class="icone"><img src="" alt="img"></div>
                            <p><?= '<strong>'.$author.'</strong><br><br>'.$remark['content'] ?></p>
                        </div>
                    <?php endforeach ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </main>
</body>
</html>