<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="assets/css/style.css">
    <title>AEOM</title>
</head>
<body>
    <!-- -------- Navigation bar ----- -->
    <header>
        <a href="index.php" class="logo">AEOM</a>
            <nav>
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="">A propos</a></li>
                    <li><a href="blog.php">Blog</a></li>
                    <li><a href="evenement.php">Évènements</a></li>
                    <li><a href="">Annonces</a></li>
                    <li><a href="">Donation</a></li>
                </ul>
            </nav>
            <div class="bloc_co">
                <?php if($objUser->getLogin() == null): ?>
                    <a href="registerUser.php"><i class="fas fa-user-circle"></i></a>
                <?php elseif($objUser->getLogin() != null): ?>
                    <a href="registerUser.php"><span><?= $objUser->getLogin() ?></span></a>
                    <a href="logOut.php"><i class="fas fa-sign-out-alt"></i></a>
                <?php endif ?>
            </div>
    </header>
    <main class="dashboard">
        <div class="container">
            <div class="side_menu">
                <ul>
                    <a href="dashbordUser.php"><li>Mes articles</li></a>
                </ul>
            </div>
            <div class="content">
                <h1>Créer un nouvelle article</h1> 
                <form action="<?= $_SERVER['PHP_SELF'] ?>" method="post" enctype="multipart/form-data">
                    <label for="title">Titre : </label><input type="text" name="title" id="title" value="<?= $title; ?>">
                    <br><br>
                    <label for="photo">Une image : </label><input type="file" name="photo[]" id="photo" value="<?= $photo ?>">
                    <br><br>
                    <label for="content">Contenu : </label><br>
                    <textarea name="content" id="content" cols="90" rows="15" ><?= $content ?></textarea>
                    
                    <?php if(isset($_GET['create'])): ?>
                        <button type="submit">Créer</button>
                    <?php elseif(isset($_GET['update'])): ?>
                        <button name="update" type="submit">Modifier</button>
                    <?php endif ?>
                </form>
            </div>
        </div>
    </main>
</body>
</html>


